[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "8kJ7zoPMNdF2EN7hS7XKmim7rpZoPwUdXNarcNmJqTZx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
